/* eslint-disable @typescript-eslint/naming-convention */
export const LanguageConstant = {
  vi: {
    // Other
    HE_THONG_QUAN_TRI: 'Hệ thống quản trị',
    THONG_TIN_CA_NHAN: 'Thông tin cá nhân',
    CAI_DAT_TRANG_CHU: 'Cài đặt Trang chủ',
    BAI_VIET_MOI: 'Mới',
    TRANG_CHU: 'Trang chủ',

    // Common
    THEM: 'Thêm mới',
    THEM_MOI_TITLE: 'Thêm mới ',
    CHINH_SUA: 'Chỉnh sửa',
    CHINH_SUA_TITLE: 'Chỉnh sửa ',
    XOA: 'Xoá',
    SO_THU_TU: 'STT',
    TRANG_THAI: 'Trạng thái',
    HOAT_DONG: 'Hoạt động',
    KHONG_HOAT_DONG: 'Không hoạt động',
    KICH_HOAT: 'Kích hoạt',
    KHONG_KICH_HOAT: 'Không kích hoạt',
    KHONG_DUOC_DE_TRONG: 'Không được để trống',
    EMAIL_ERROR_FIELD: 'Không đúng định dạng email',
    HUY: 'Huỷ',
    LUU: 'Lưu',
    LUU_VA_DUYET: 'Lưu và duyệt',
    SAN_SANG: 'Sẵn sàng',
    DONG: 'Đóng',
    KHONG_DUYET: 'Không duyệt',
    HUY_CHUYEN: 'Hủy chuyến',
    TAI_LEN: 'Tải lên',
    DUYET_THANH_CONG: 'Duyệt thành công',
    GUI: 'Gửi',
    XAC_NHAN_THAY_DOI_TRANG_THAI: 'Xác nhận thay đổi trạng thái?',
    XAC_NHAN: 'Xác nhận',
    THAY_DOI_THANH_CONG: 'Thay đổi thành công!',
    CO_LOI_XAY_RA: 'Có lỗi xảy ra, vui lòng thử lại!',
    THEM_MOI_THANH_CONG: 'Thêm mới thành công!',
    CAP_NHAT_THANH_CONG: 'Cập nhật thành công!',
    MAT_KET_NOI_SERVER: 'Không thể kết nối đến máy chủ!',
    TAI_KHOAN_KHONG_CO_QUYEN: 'Tài khoản không có quyền truy cập!',
    DANG_KY_THANH_CONG: 'Đăng ký thành công',
    XEM_TRUOC: 'Xem trước',
    ANH: 'ảnh (Click để xoay)',
    DANG_TAI: 'Đang tải, vui lòng chờ...',
    CHON_TEP: 'Chọn tệp',
    CHON_TEP_KHAC: ' khác',
    CHUA_CO_TEP_TIN: 'Chưa có tệp tin',

    // Paging
    SO_BAN_GHI: 'Số bản ghi',
    TRANG: 'Trang',
    TONG_SO: 'Tổng số',
    BAN_GHI: 'bản ghi',

    // Homepage
    TIM_KIEM: 'Tìm kiếm',
    THONG_BAO: 'Thông báo',
    XEM_THEM: 'Xem thêm',
    DANH_MUC: 'Danh mục',


    // Header
    DANG_NHAP: 'Đăng nhập',
    DE_TAI: 'Đề tài',
    TAI_KHOAN: 'Tài khoản',
    DANG_XUAT: 'Đăng xuất',
    QUAN_TRI: 'Quản trị',
    CONG_VIEC: 'Công việc',

    // Main footer
    DESIGN_BY_COST: 'Thiết kế & Phát triển bởi COST - HCMUTE',
    THONG_TIN_TRUONG_1: 'Trường Đại Học Sư Phạm Kỹ Thuật',
    THONG_TIN_TRUONG_2: 'Thành Phố Hồ Chí Minh',
    THONG_TIN_KHOA: 'Khoa Cơ khí - Chế Tạo Máy',
    LIEN_HE_CHUNG_TOI: 'Liên hệ với chúng tôi',
    PHONG_BAN: 'Phòng E00, Khu E',
    DIA_CHI_1: '01 Võ Văn Ngân, Linh Chiểu',
    DIA_CHI_2: 'Thủ Đức, TP. HCM',
    SO_DIEN_THOAI_LIEN_HE: '(+84) 28 3896 1141',
    EMAIL_LIEN_HE: 'fme@hcmute.edu.vn',

    // Login page
    QUYEN_HE_THONG: 'Quyền hệ thống',
    CHUA_NHAP_TEN_DANG_NHAP: 'Vui lòng nhập Tên đăng nhập',
    CHUA_NHAP_MAT_KHAU: 'Vui lòng nhập Mật khẩu',
    GHI_NHO_DANG_NHAP: 'Ghi nhớ đăng nhập',
    QUEN_MAT_KHAU: 'Quên mật khẩu?',
    // DANG_NHAP: 'Đăng nhập',
    HOAC: 'Hoặc',
    DANG_NHAP_GOOGLE: 'Đăng nhập bằng Google',
    TEN_DANG_NHAP: 'Tên đăng nhập',
    MAT_KHAU: 'Mật khẩu',
    LUU_Y_DANG_NHAP_GOOGLE: 'Bạn sẽ đăng nhập với quyền hệ thống đã chọn phía trên',
    PHAN_QUYEN_KHONG_TON_TAI: 'Phân quyền không tồn tại!',
    QUYEN_HAN_KHONG_HO_TRO_DANG_NHAP_FORM: 'Vui lòng Đăng nhập bằng Google với quyền hạn này!',

    // Admin sidebar
    TONG_QUAN: 'Tổng quan',
    LINH_VUC: 'Lĩnh vực',

    // DANH_MUC: 'Danh mục',
    HOC_HAM: 'Học hàm',
    CAU_HINH: 'Cấu hình',
    EMAIL_GUI_THU: 'Email gửi thư',


    //Đăng kí tham quan
    TOURS: 'Chuyến tham quan',
    DONG_THOI_GIAN: 'Dòng thời gian',
    DANG_KY_THAM_QUAN: 'Đăng ký tham quan',
    TEN_GV: 'Tên giảng viên',
    EMAIL: 'Email',
    SDT: 'Số điện thoại',
    NOI_DUNG_THAM_QUAN: 'Nội dung tham quan',
    KHOA: 'Khoa',
    NGANH: 'Ngành',
    SO_LUONG_SV: 'Số lượng sinh viên',
    SV_NAM_THU: 'Sinh viên năm',
    GIANG_VIEN: 'Giảng viên',
    GIANG_VIEN_KHOA: 'Giảng viên khoa',
    SO_LUONG_GV_THAM_GIA: 'Số lượng giảng viên tham gia',
    THOI_GIAN_DU_KIEN: 'Thời gian dự kiến',
    TEN_CONG_TY: 'Tên công ty',
    DIA_CHI_CTY: 'Địa chỉ công ty',
    SDT_LIEN_HE_CONG_TY: 'Số điện thoại liên hệ công ty',
    HOC_KY: 'Học kỳ',
    NAM_HOC: 'Năm học',
    YEU_CAU_CONG_VAN: 'Yêu cầu công văn',
    DA_LIEN_HE: 'Đã liên hệ',
    CHUA_LIEN_HE: 'Chưa liên hệ',
    TU_NGAY: 'Từ ngày',
    DEN_NGAY: 'Đến ngày',
    HOC_KY_1: 'Học kỳ 1',
    HOC_KY_2: 'Học kỳ 2',
    CHON_KHOA: 'Chọn khoa',
    CO_THUE: 'Có thuê',
    KHONG_THUE: 'Không thuê',

    // Admin Hoc Ham
    // HOC_HAM: 'Học Hàm',
    TEN_HOC_HAM: 'Tên học hàm',
    TEN_VIET_TAT: 'Tên viết tắt',
    TEN_HOC_HAM_VN: 'Tên học hàm ',
    TEN_VIET_TAT_VN: 'Tên viết tắt ',
    TEN_HOC_HAM_EN: 'Tên học hàm ',
    TEN_VIET_TAT_EN: 'Tên viết tắt ',

    // Admin Hoc Vi
    // HOC_VI: 'Học Vị',
    HOC_VI: 'Học vị',
    TEN_HOC_VI: 'Tên học vị',
    TEN_HOC_VI_VIET_TAT: 'Tên viết tắt',
    TEN_HOC_VI_VN: 'Tên học vị ',
    TEN_HOC_VI_EN: 'Tên học vị ',

    //Admin Linh Vuc
    // LINH_VUC:'Lĩnh vực',
    MA_LINH_VUC: 'Mã lĩnh vực',
    TEN_LINH_VUC: 'Tên lĩnh vực',
    TEN_LINH_VUC_VN: 'Tên lĩnh vực ',
    TEN_LINH_VUC_EN: 'Tên lĩnh vực ',

    //Admin Khoa
    //KHOA: 'Khoa',
    THU_TU: 'Thứ tự',
    MA_KHOA: 'Mã khoa',
    TEN_KHOA: 'Tên khoa',
    TEN_KHOA_VN: 'Tên khoa ',
    TEN_KHOA_EN: 'Tên khoa ',


    // Admin Nganh
    // NGANH: 'Ngành',
    STT: 'Số thứ tự',
    MA_NGANH: 'Mã ngành',
    TEN_NGANH_VN: 'Tên ngành ',
    TEN_NGANH: 'Tên ngành',
    TEN_NGANH_EN: 'Tên ngành ',
    DIEM_DO_AN: 'Điểm đồ án ',
    TEN_DO_AN: 'Tên đồ án',
    THEM_DO_AN: 'Thêm đồ án',
    //Admin Sender Email
    EMAIL_NHAN_THU: 'Email nhận thư',
    CAU_HINH_HE_THONG_CHUNG: 'Cấu hình chung',
    PASSWORD_EMAIL_GUI_THU: 'Password email gửi thư',
    NHAP_LAI_MAT_KHAU: 'Nhập lại password',
    MAT_KHAU_KHONG_TRUNG_KHOP: 'Mật khẩu không trùng khớp',
    PHU_CAP_CONG_TAC_VIEN: 'Phụ cấp cộng tác viên',
    PHU_CAP_LON_HON_HOAC_BANG_0: 'Phụ cấp phải lớn hơn hoặc bằng 0',
    //Đăng kí dẫn đoàn
    HO_VA_TEN: 'Họ và tên',
    //Nộp bài thu hoạch
    NOP_BAI_THU_HOACH: 'Nộp bài thu hoạch',
    MSSV: 'Mã số sinh viên',
    GIANG_VIEN_PHU_TRACH: 'Giảng viên phụ trách',
    THOI_GIAN_PHU_TRACH: 'Thời gian phụ trách',

    //Admin địa điểm
    DIA_DIEM: 'Địa điểm',
    TEN_DIA_DIEM: 'Tên địa điểm',

    //Admin đợt tham quan
    DOT_THAM_QUAN: 'Đợt tham quan',
    TEN_DOT_THAM_QUAN: 'Tên đợt tham quan',
    NGAY_BAT_DAU: 'Ngày bắt đầu',
    NGAY_KET_THUC: 'Ngày kết thúc',
    DANG_KY: 'Đăng ký',
    DA_DANG_KY: 'Đã đăng ký',
    HUY_DANG_KY: 'Hủy đăng ký',
    CHO_DUYET: 'Chờ duyệt',
    CHON_HOC_KY: 'Chọn học kỳ',
    HK1: 'HK1',
    HK2: 'HK2',
    MUC_DICH: 'Mục đích',
    YEU_CAU: 'Yêu cầu',

    //Checkin
    DIEM_DANH: 'Điểm danh',
    DIEM_DANH_CTV: 'Điểm danh cộng tác viên',
    DIEM_DANH_SINH_VIEN: 'Điểm danh sinh viên',
    MA_CONG_TAC_VIEN: 'Mã cộng tác viên',
    VIEW_FILE: 'View file',
    FILE_CHECK_IN: 'File check in',
    FILE_CHECK_OUT: 'File check out',
    SO_PHUT_DI_TRE: 'Số phút đi trễ',
    THOI_GIAN_DIEM_DANH: 'THời gian điểm danh',
    DA_DIEM_DANH: 'Đã điểm danh',
    CHUA_DIEM_DANH: 'Chưa điểm danh',
    QUET_QRCODE: 'Điểm danh bằng QR Code?',
    CO: 'Có',
    KHONG: 'Không',
    //Upload file
    UPLOAD_IMG: 'Tải ảnh',

    //Phương tiện
    PHUONG_TIEN: 'Phương tiện',
    BIEN_SO: 'Biển số',
    MAU_XE: 'Màu xe',
    SO_CHO_NGOI: 'Số chỗ ngồi',
    TEN_XE: 'Tên xe',
    XOA_PHUONG_TIEN: 'Xóa phương tiện',

    /////// User//////
    MANAGEMENT_USER: 'Quản lý người dùng',
    // COLLABORATOR & EXPERT
    COLLABORATOR: 'Cộng tác viên',
    EXPERT: 'Chuyên viên',
    MANAGEMENT_COLLABORATOR: 'Quản lý cộng tác viên',
    MANAGEMENT_EXPERT: 'Quản lý chuyên viên',
    ENTER_YOUR_NAME: 'Nhập họ và tên',
    GENDER: 'Giới tính',
    MALE: 'Nam',
    FEMALE: 'Nữ',
    CHOOSE_GENDER: 'Chọn giới tính',
    ENTER_YOUR_EMAIL: 'Vui lòng nhập email',
    EMAIL_NOT_CORRECT: 'Email chưa đúng định dạng',
    PHONE: 'Điện thoại',
    ENTER_YOUR_PHONE: 'Vui lòng nhập số điện thoại',
    PHONE_NOT_CORRECT: 'Số điện thoại không đúng',
    ENTER_STUDENT_ID: 'Nhập MSSV',
    CHOOSE_FACULTY: 'Chọn khoa',
    CHOOSE_MAJORS: 'Chọn ngành học',
    STAFF_ID: 'MSCB',
    ENTER_STAFF_ID: 'Nhập MSCB',


    //Admin chuyến tham quan
    //TOURS: 'Chuyến tham quan'
    CHUYEN_THAM_QUAN: 'Chuyến tham quan',
    TEN_CHUYEN_THAM_QUAN: 'Tên chuyến tham quan',
    THOI_GIAN_KHOI_HANH: 'Thời gian khởi hành',
    DIA_DIEM_KHOI_HANH: 'Địa điểm khởi hành',
    DOANH_NGHIEP: 'Doanh nghiệp',
    THOI_GIAN_BAT_DAU_THAM_QUAN: 'Thời gian bắt đầu',
    THOI_GIAN_KET_THUC_THAM_QUAN: 'Thời gian kết thúc',
    DANH_SACH_CONG_TAC_VIEN: 'Danh sách cộng tác viên',
    DANH_SACH_SINH_VIEN: 'Danh sách sinh viên',
    CONG_TAC_VIEN: 'Cộng tác viên',
    KINH_PHI: 'Kinh phí',
    THUE_XE_NGOAI_TRUONG: 'Thuê xe ngoài trường',
    DANH_SACH_TOUR_CHO_DUYET: 'Danh sách tour chờ duyệt',
    DANH_SACH_TOUR_DANG_XU_LY: 'Danh sách tour đang xử lý',
    DANH_SACH_TOUR_SAN_SANG: 'Danh sách tour sẵn sàng',
    DANH_SACH_TOUR_CHUA_CO_DOT: 'Danh sách tour chưa có đợt tham quan',
    DANH_SACH_TOUR_KHONG_DUYET: 'Danh sách tour không duyệt',
    DANH_SACH_TOUR_DA_HOAN_TAT: 'Danh sách tour đã hoàn tất',
    CAP_NHAT_LY_DO_KHONG_DUYET: 'Cập nhật lý do không duyệt',
    LY_DO_KHONG_DUYET: 'Lý do không duyệt',
    KHONG_THE_IMPORT_MOT_SO_SV: 'Thông tin một số sinh viên không hợp lệ, vui lòng xem trong danh sách trả về!',
    NHAP_DANH_SACH_SV_THANH_CONG: 'Nhập danh sách sinh viên thành công',
    GIANG_VIEN_DANG_KY: 'Giảng viên đăng ký',
    CHON_CONG_TAC_VIEN: 'Chọn cộng tác viên',
    CHON_PHUONG_TIEN: 'Chọn phương tiện',
    CHON_DOANH_NGHIEP: 'Chọn doanh nghiệp',
    CHON_DOT_THAM_QUAN: 'Chọn đợt tham quan',
    CHON_GIANG_VIEN: 'Chọn giảng viên',
    CHON_DIA_DIEM: 'Chọn địa điểm',
    CAP_NHAT_THONG_TIN: 'Cập nhật thông tin',
    CAP_NHAT_DSSV: 'Cập nhật DSSV',
    CAP_NHAT_DSCTV: 'Cập nhật DS CTV',
    DANH_SACH_SINH_VIEN_THAM_QUAN: 'Danh sách sinh viên tham quan',
    NHAP_DANH_SACH: 'Nhập danh sách sinh viên',
    TAI_MAU_IMPORT_SV: 'Tải mẫu import danh sách sinh viên',
    TAI_MAU_IMPORT_DIEM_DANH_SV: 'Tải mẫu import điểm danh sinh viên',
    NHAP_DS_DIEM_DANH_BU: 'Nhập danh sách điểm danh bù',
    DIEM_DANH_BU: 'Điểm danh bù',
    CHON_SINH_VIEN: 'Chọn sinh viên',
    XAC_NHAN_DANG_KY: 'Xác nhận đăng ký',
    XAC_NHAN_HUY_DANG_KY: 'Xác nhận hủy đăng ký',
    DIA_DIEM_DON: 'Địa điểm đón',
    DIA_DIEM_DEN: 'Địa điểm đến',
    THONG_TIN_CHUYEN_THAM_QUAN: 'Thông tin chuyến tham quan',
    THONG_TIN: 'Thông tin',
    HUY_THANH_CONG: 'Hủy thành công',
    FILE_XAC_NHAN_BAN_GIAM_HIEU: 'File xác nhận của ban giám hiệu',
    TAO_DOT: 'Tạo đợt',
    DA_DUYET: 'Đã duyệt',
    SAO_LUU: 'Sao lưu',
    FILE_XAC_NHAN_DOANH_NGHIEP: 'File xác nhận của doanh nghiệp',
    FILE_KE_HOACH: 'File kế hoạch',
    LINK_FILE: 'Link file',
    CAP_NHAT_THONG_TIN_SAO_LUU: 'Cập nhật thông tin sao lưu',
    XEM_DSSV: 'Xem DSSV',
    XEM_DSCTV: 'Xem DS CTV',
    XEM_THONG_TIN: 'Xem thông tin',
    TIM_KIEM_NANG_CAO: 'Tìm kiếm nâng cao',
    AN_TIM_KIEM_NANG_CAO: 'Ẩn tìm kiếm nâng cao',
    CAP_NHAT_FILE: 'Cập nhật file',

    //Admin Văn bản biểu mẫu
    DOCUMENTS: 'Văn bản biểu mẫu',
    TEN_BIEU_MAU: 'Tên biểu mẫu',
    TEN_BIEU_MAU_EN: 'Tên biểu mẫu ',
    FILE: 'File',



    //Admin Manage user
    //SINH_VIEN
    USERS: 'Quản lý người dùng',
    SINH_VIEN: 'Sinh viên',
    QUAN_LY_SINH_VIEN: 'Quản lý sinh viên',
    HO_TEN: 'Họ tên',
    LOP: 'Lớp',
    GIOI_TINH: 'Giới tính',
    NGAY_SINH: 'Ngày sinh',
    DIEN_THOAI: 'Số điện thoại',
    CHON_NGANH: 'Chọn ngành',
    CMND: 'Chứng minh nhân dân',
    MSSV_PHAI_LON_HON_0: 'MSSV phải lớn hơn 0',

    //Admin doanh nghiệp
    // DOANH_NGHIEP: 'Doanh nghiệp',
    CONG_TY: 'Tên công ty',
    EMAIL_CONG_TY: 'Email công ty',
    HO_TEN_CHU_CONG_TY: 'Họ tên chủ công ty',
    NAM: 'Nam',
    NU: 'Nữ',
    SO_DIEN_THOAI: 'Số điện thoại',
    DIA_CHI: 'Địa chỉ',
    MA_SO_THUE: 'Mã số thuế',
    QUYEN_HAN: 'Quyền',
    QUYEN_QUAN_TRI: 'Quyền quản trị',
    QUYEN_DOANH_NGHIEP: 'Quyền doanh nghiệp',
    QUYEN_CONG_TAC_VIEN: 'Quyền cộng tác viên',
    CHON_QUYEN: 'Chọn quyền',
    CHON_LINH_VUC: 'Chọn lĩnh vực',


    // Admin management file
    MANAGEMENT_FILE: 'Quản lý file HDSD',
    FILE_MANUALS: 'File hướng dẫn',
    TITLE: 'Tiêu đề',
    ENTER_TITLE: 'Vui lòng nhập tiêu đề',

    // Backup tours
    LUU_TRU_HO_SO: 'Lưu trữ hồ sơ',
    BUSINESS_CONFIRMATION: 'Xác nhận của doanh nghiệp',
    PHOTO_OF_TOUR: 'Ảnh của chuyến tham quan',
    BACKUP_TOURS: 'Sao lưu chuyến tham quan',


    //KHAO_SAT
    KHAO_SAT: 'Khảo sát',
    KHAO_SAT_SINH_VIEN: 'Khảo sát sinh viên',
    KHAO_SAT_DOANH_NGHIEP: 'Khảo sát doanh nghiệp',
    KHAO_SAT_CTV: 'Khảo sát cộng tác viên',


    //KHAO_SAT
    CAU_HOI_KHAO_SAT_SINH_VIEN: 'Câu hỏi khảo sát sinh viên',
    CAU_HOI_KHAO_SAT_DOANH_NGHIEP: 'Câu hỏi khảo sát doanh nghiệp',
    CAU_HOI_KHAO_SAT_CTV: 'Câu hỏi khảo sát cộng tác viên',
    CAU_HOI: 'Câu hỏi',
    LOAI_CAU_HOI: 'Loại câu hỏi',
    LUA_CHON_TOI_DA: 'Lựa chọn tối đa',
    DANH_SACH_LUA_CHON: 'Danh sách lựa chọn',
    SAP_XEP_DANH_SACH: 'Sắp xếp danh sách theo thứ tự ưu tiên giảm dần',
    CAU_HOI_BAT_BUOC: 'Câu hỏi bắt buộc',
    NOI_DUNG_LUA_CHON: 'Nội dung lựa chọn',
    CHON_LOAI_CAU_HOI: 'Chọn loại câu hỏi',
    CHON_MOT: 'Chọn một',
    CHON_NHIEU: 'Chọn nhiều',
    SAP_XEP: 'Sắp xếp lựa chọn',
    NHAP_LIEU: 'Nhập liệu',
    VUI_LONG_CHO: 'Vui lòng chờ...',
    PHAI_HOAN_TAT_CAU_HOI_BAT_BUOC: 'Vui lòng hoàn tất các câu hỏi bắt buộc!',
    KHONG_NHO_HON_1: 'Không được nhỏ hơn 1',
    NHAP_CAU_TRA_LOI: 'Nhập câu trả lời',
    THEM_LUA_CHON: 'Thêm lựa chọn',
    THUC_HIEN_KHAO_SAT: 'Thực hiện khảo sát',
    DANH_SACH_CAU_HOI_KHAO_SAT: 'Danh sách câu hỏi khảo sát',
    NOP: 'Nộp',
    THUC_HIEN_KHAO_SAT_THANH_CONG: 'Thực hiện khảo sát thành công',
    KHAO_SAT_DA_DUOC_THUC_HIEN: 'Khảo sát đã được thực hiện',
    // FULL-CALENDAR
    F_HOM_NAY: 'Hôm nay',
    F_NAM: 'Năm',
    F_THANG: 'Tháng',
    F_TUAN: 'Tuần',
    F_NGAY: 'Ngày',
    F_THU_HAI: 'Thứ Hai',
    F_THU_HAI_VT: 'T2',
    F_THU_BA: 'Thứ Ba',
    F_THU_BA_VT: 'T3',
    F_THU_TU: 'Thứ Tư',
    F_THU_TU_VT: 'T4',
    F_THU_NAM: 'Thứ Năm',
    F_THU_NAM_VT: 'T5',
    F_THU_SAU: 'Thứ Sáu',
    F_THU_SAU_VT: 'T6',
    F_THU_BAY: 'Thứ Bảy',
    F_THU_BAY_VT: 'T7',
    F_CHU_NHAT: 'Chủ Nhật',
    F_CHU_NHAT_VT: 'CN',
    F_THOI_GIAN: 'Thời gian',

    TRANG_THAI_CHUYEN_THAM_QUAN: 'Trạng thái chuyến tham quan',

    THONG_KE: 'Thống kê',
    // QL Giảng viên
    MANAGEMENT_LECTURERS: 'Quản lý giảng viên',
    LECTURERS: 'Giảng viên',
    LECTURERS_ID: 'Mã giảng viên',
    ENTER_LECTURERS_ID: 'Nhập mã giảng viên',
    THINH_GIANG: 'Thỉnh giảng',

    //CTV
    DIEM_DANH_THAM_QUAN: 'Điểm danh tham quan',

    //THONG KE
    CAU_TRA_LOI: 'Câu trả lời',
    THONG_KE_THEO: 'Thông kế theo',
    CHON_KHOANG_NAM: 'Chọn khoảng năm',
    THEO_MOC_THOI_GIAN: 'Theo mốc thời gian',
    THEO_DOANH_NGHIEP: 'Theo doanh nghiệp',
    CAU_TL_DOANH_NGHIEP_LOAI_NHAP_LIEU: 'Câu trả lời doanh nghiệp loại câu hỏi nhập liệu',
    CAU_TL_DOANH_NGHIEP_LOAI_LUA_CHON: 'Câu trả lời doanh nghiệp loại câu hỏi lựa chọn',
    CAU_TL_DOANH_NGHIEP_LOAI_SAP_XEP: 'Câu trả lời doanh nghiệp loại câu hỏi sắp xếp',
    CAU_TL_SINH_VIEN_LOAI_LUA_CHON: 'Câu trả lời sinh viên loại câu hỏi lựa chọn',
    CAU_TL_SINH_VIEN_LOAI_NHAP_LIEU: 'Câu trả lời sinh viên loại câu hỏi nhập liệu',
    CAU_TL_SINH_VIEN_LOAI_SAP_XEP: 'Câu trả lời sinh viên loại câu hỏi sắp xếp',
    CAU_TL_CTV_LOAI_LUA_CHON: 'Câu trả lời công tác viên loại câu hỏi lựa chọn',
    CAU_TL_CTV_LOAI_NHAP_LIEU: 'Câu trả lời cộng tác viên loại câu hỏi nhập liệu',
    CAU_TL_CTV_LOAI_SAP_XEP: 'Câu trả lời cộng tác viên loại câu hỏi sắp xếp',
    THU_TU_UU_TIEN: 'Thứ tự ưu tiên',
    THONG_KE_THEO_CAU_TRA_LOI: 'Thống kê theo câu trả lời',
    CHON_CHUYEN_THAM_QUAN: 'Chọn chuyến tham quan',

    NHAP_QUYET_DINH_BGH: 'File quyết định của BGH',
    NHAP_QUYET_DINH_BGH_THANH_CONG: 'Nhập file quyết định của BGH thành công!',
    NHAP_DS_DIEM_DANH_THANH_CONG: 'Nhập danh sách điểm danh thành công!',

    //POST
    BAI_VIET: 'Bài viết',
    CHON_CHUYEN_MUC: 'Chọn chuyên mục',
    CHUYEN_MUC: 'Chuyên mục',
    TAT_CA_CHUYEN_MUC: 'Tất cả chuyên mục',
    LOAI_BAI_VIET: 'Loại vài viết',
    CHON_LOAI_BAI_VIET: 'Chọn loại vài viết',
    TEN_BAI_VIET: 'Tên bài viết',
    TEN_BAI_VIET_VN: 'Tên bài viết (Tiếng Việt)',
    TEN_BAI_VIET_EN: 'Tên bài viết (Tiếng Anh)',
    NOI_DUNG_BAI_VIET_VN: 'Nội dung (Tiếng Việt)',
    NOI_DUNG_BAI_VIET_EN: 'Nội dung (Tiếng Anh)',
    ANH_BIA_BAI_VIET: 'Ảnh bìa',
    CHON_ANH_BAI_VIET: 'Chọn ảnh bìa',
    CAT_ANH_BAI_VIET: 'Cắt ảnh bìa',
    ANH_BAI_VIET_HIEN_THI: 'Ảnh hiển thị',
    DANH_SACH_BAI_DANG: 'Danh sách bài đăng',
    NGAY_DANG: 'Ngày đăng',
    TAI_THEM: 'Tải thêm',

    BANNER: 'Banner',
    TIEU_DE: 'Tiêu đề',
    CHON_ANH_BANNER: 'Chọn ảnh banner',
    CAT_ANH_BANNER: 'Cắt ảnh banner',
    BANNER_HIEN_THI: 'Banner hiển thị',
    CO_LOI_KHI_TAI_LEN: 'Có lỗi khi tải lên, vui lòng thử lại!',
    CANH_BAO_ANH_CHAT_LUONG_THAP: 'Chú ý: Ảnh này có kích thước quá nhỏ, kích thước khuyến nghị là 1120px x 400px → 2240px x 800px.',
    CANH_BAO_ANH_CHAT_LUONG_CAO: 'Chú ý: Ảnh này có kích thước quá lớn, sẽ ảnh hưởng đến tốc độ tải trang, ' +
      'kích thước khuyến nghị là 1120px x 400px → 2240px x 800px.',
    ANH_XEM_TRUOC: 'Ảnh xem trước',
    CHON_ANH_MOI: '(Cần chọn ảnh mới nếu cần thay đổi hoặc cắt lại ảnh)',
    LIEN_KET_NGOAI: 'Liên kết ngoài',
    LIEN_KET_KHONG_DUNG_DINH_DANG: 'Liên kết phải bắt đầu bằng http:// hoặc https://',

    SIDE_BANNER: 'Banner cạnh',

    CHUYEN_MUC_BAI_VIET: 'Chuyên mục bài viết',
    CUOI_DANH_SACH: 'Cuối danh sách',
    HAY_CHON_MOT_MUC: 'Hãy chọn một mục!',
    CHUA_CO_NOI_DUNG: 'Chưa có nội dung nào!',
  },


  en: {},
};
